"""Initial tables

Revision ID: 5f3bd912225b
Revises: 
Create Date: 2025-09-15 00:06:12.504147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3bd912225b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_provider_id'), 'providers', ['provider_id'], unique=True)
    op.create_index(op.f('ix_providers_zip_code'), 'providers', ['zip_code'], unique=False)
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('ms_drg_definition', sa.String(), nullable=True),
    sa.Column('total_discharges', sa.Integer(), nullable=True),
    sa.Column('average_covered_charges', sa.Float(), nullable=True),
    sa.Column('average_total_payments', sa.Float(), nullable=True),
    sa.Column('average_medicare_payments', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_ms_drg_definition'), 'procedures', ['ms_drg_definition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedures_ms_drg_definition'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_providers_zip_code'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
